<a href="https://colab.research.google.com/github/giwon1115/2025-1-myclass-BDA/blob/main/02w_A_0317_pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 시리즈활용

In [1]:
import numpy as np
import pandas as pd

s=['희빈','수영','현수','지호','지민']
p=pd.Series([99,84,92,65,76],index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    76
dtype: int64

In [ ]:
p.name='수학성적'
p.index.name='이름'
p

이름
희빈    99
수영    84
현수    92
지호    65
지민    76
Name: 수학성적, dtype: int64

In [ ]:
p.sort_index() # ㅅ ㅇ ㅈ ㅎ 순서

이름
수영    84
지민    76
지호    65
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [ ]:
p.sort_index(ascending=False)

이름
희빈    99
현수    92
지호    65
지민    76
수영    84
Name: 수학성적, dtype: int64

In [ ]:
p.sort_values(ascending=False)

이름
희빈    99
현수    92
수영    84
지민    76
지호    65
Name: 수학성적, dtype: int64

##시리즈 기본 통계함수

In [ ]:
print(p.max())
print(p.min())
print(p.mean())
print(p.median())
print(p.count())
print(p.size)

99
65
83.2
84.0
5
5

In [ ]:
p.describe()

count     5.000000
mean     83.200000
std      13.330416
min      65.000000
25%      76.000000
50%      84.000000
75%      92.000000
max      99.000000
Name: 수학성적, dtype: float64

In [ ]:
s=pd.Series([3,1,1,2,None,np.nan,4,6,6,np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [ ]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [ ]:
s.count()

7

In [ ]:
s.value_counts()

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [ ]:
s.value_counts(dropna=False)#가장 많은게 먼저

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [ ]:
s.value_counts(dropna=False,sort=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [ ]:
s.value_counts(bins=4)

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [ ]:
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [ ]:
s.value_counts(bins=4,sort=False)

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [ ]:
s.value_counts(bins=[0.5,3.5,6.5],sort=False)

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

##데이터프레임 기초

In [57]:
import pandas as pd
df=pd.DataFrame=([10,20,30,40,50])
df

[10, 20, 30, 40, 50]

In [ ]:
type(df)

list

In [3]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]],index=list('abc'))
df

     0    1    2
a    1    2    3
b   10   20   30
c  100  200  300

In [ ]:
list('abc')

['a', 'b', 'c']

In [18]:
df=pd.DataFrame([[1,2,3],[10,20,30],[100,200,300]],index=list('abc'),columns=['A','B','C'])
df

     A    B    C
a    1    2    3
b   10   20   30
c  100  200  300

In [5]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [6]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [7]:
df=pd.DataFrame(data=np.arange(12).reshape(2,6))
df

   0  1  2  3   4   5
0  0  1  2  3   4   5
1  6  7  8  9  10  11

In [8]:
df1=pd.DataFrame(data=np.random.randint(1,46,(5,6)))
df1

    0   1   2   3   4   5
0  39  34  12  38  35  29
1   3  28  13  16  40  18
2  21   5   8  22  21  38
3   7   7  26  22  19  34
4   4  23  29  26  14  11

In [9]:
np.random.seed(100)
df1=pd.DataFrame(data=np.random.randint(1,46,(5,6)))
df1

    0   1   2   3   4   5
0   9  25   4  40  24  16
1  11  31  35   3  35  15
2  35  25  16  37  44  17
3  10  30  23   3  28  45
4   5  32   2  14  20  37

In [11]:
df1=pd.DataFrame(data=np.random.random((5,3)))
df1

          0         1         2
0  0.442254  0.030123  0.776005
1  0.550958  0.381073  0.529266
2  0.956877  0.175821  0.118303
3  0.862946  0.074867  0.825095
4  0.836132  0.075395  0.011401

In [20]:
df=pd.DataFrame({'numbers':[1,2,3],'colors':['red','white','blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [13]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [14]:
df.columns

RangeIndex(start=0, stop=6, step=1)

In [23]:
df=pd.dataFrame({'국어':[87,76,67],'수학':[99,87,78]},index=['김국진','신영희','김일순'])
df

AttributeError: module 'pandas' has no attribute 'dataFrame'

In [16]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [17]:
df.columns

RangeIndex(start=0, stop=6, step=1)

In [ ]:
courses=pd.Series(['spark','pyspark','hadoop'],name='courses')
courses

0      spark
1    pyspark
2     hadoop
Name: courses, dtype: object

In [ ]:
fees=pd.Series([250000,300000,200000],name='fees')
fees

0    250000
1    300000
2    200000
Name: fees, dtype: int64

In [24]:
df=pd.DataFrame({courses.name:courses,fees.name=fees})

SyntaxError: ':' expected after dictionary key (<ipython-input-24-ff30cffd5287>, line 1)